# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 21:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subdomain', models.TextField(db_index=True, unique=True, validators=[restaurants.models.validate_subdomain])),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('postal_code', models.TextField(blank=True, default=None, null=True)),
                ('city', models.TextField(blank=True, default=None, null=True)),
                ('phone_number', models.TextField(blank=True, default=None, null=True)),
                ('email', models.TextField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
