# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
