language: python
branches:
  only:
    - master
    - /^feature_.*$/
services:
  - postgresql
python:
  - '3.4'
addons:
  postgresql: "9.4"
install:
  - pip install -r requirements.txt
  - npm install
before_script:
  - python manage.py makemigrations --settings=fud.settings.travis
  - python manage.py migrate --settings=fud.settings.travis
  - psql -c 'create database fud_test;' -U postgres
  - gulp build
script:
  - python manage.py test --settings=fud.settings.travis
notifications:
  email: false
  flowdock:
    secure: RDmpEAIiUz7IbecJ4fI6w+CqhuKTZMI8t8FOYiyQez8WGv37vSzKzo9SnDqgcgEYOfDTIgVxr2nx0F8nZWfK5o1AVnm9Wy5gYGWuZorz5/wlfhccOoRVyhbn7L2Vf4Bp3Km0BvybyxapOyy3/GMqBwbtgW6tKvIxjo+8X4uo3A9D8ex2QIpI9zHGKJ9tSn8QEYjNHH6V5UuV8PFrX39J3iEzBIKMoBsaUQF0Rsw7aNXYLwxMocyQBLGU813Y089yeAnlR9ud90zpFVXodjbong4p5DIaEfTjCTv1SHwba2NMkqm9Ge8xC6gqVLsYVt9S9tJRC35gu//gnis1AoS3QFdDfWfN55/HgMdTPlMMHofQEaG8gQDbpBRT+QEAg/TpiR2vU125Muia2a1KLNEvdzY2A8nX1JzlQSQo/eqJ06rnnLjEc9Tg/+2gW2mTI7BdVvUebNpddYD3Z3Dq2cPRBACBYkVTZ9+baOORtpZ0G/LlHICR/d1t+7nDzQxvhsrEv2RLpWbZxdIoC03yO5ts0sM+Wnw+cHN0g559Dowq0/WNOwcjo1S7FkGFbUnM4eDfe3GeZrs3Bby6PyyyhTYOuiuDffR1x6msf1VVQK1JQHaSSs/BJobN1QrtoRGhekr0fp5kiudQquGBp6LecPTL7rkciY5J9JcdyKUtxzaoDi8=
cache:
  directories:
    - $HOME/.cache/pip
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
    - node_modules
