language: python
branches:
  only:
    - master
    - /^feature_.*$/
services:
- postgresql
python:
- '3.4'
addons:
  postgresql: "9.3"
install:
- pip install -r requirements.txt
before_script:
  - psql -c 'create database fud_test;' -U postgres
  - echo y | ./get-djoser.sh
script:
  - python manage.py test --settings=fud.settings.travis
notifications:
  email: false
  flowdock:
    secure: "TclleJBz8iD+yfJ2S0T9MUca13G7YrHcH/pLtyHL6BGPPDok4aGldLOLI3BM948AuOzH5HVIWbcR4sJ1RuyS59zhDeVuvvg9nzQsdfRgb5VToqn3jUtKYdZF006wbAG/pnnYpd4tHcEOLBFZ7fJDoyJO0PDroLZD2fy0GwDVWQ6r91O69MuH1pZRAPd94RrZtl4xhdX4GejUy3Z9IGSolVwsJEZ+T5EAhYmoAYMGXKIe3uOMLDS9mVqvPJ8SeFCdGATn8iyFvnLxrP3AZiU2c22i+megH24qFZM8efwArx9AORMmANt4LspjXI8RCD1mNMtRJ5j7gWZkjwytaqu9iVFJXNEuBx2iJNxIrRBtOWGhsx95mgF9pywrlhftmTBtPip0xJjOwWl5Rl2nPCNJyrm8Q66FOx5PTkf/YGfeBRj1KrRSarafr2cdoLViu3g6piwSAGNBVNeIpKH6klXyWJTJysZxkMYEqxFBGq5MxUUk21f2e79S4cwR4WrRsLvlFE/FH87H6J4Go8pe7THy0B2TJBWViHAcgF19RpJHBxzDMqqCMZ8UKYq2HtZMTN2NVIct0TWLLtuAkJ1JcgMcsA1LgY53g9W4KKgwRCZf97YJEGygh9EE5zEGVXGrW6FmLx/f9iQiPtHOJYu22AoZ+9/afEeaQifD3Z3OAd/WP/I="
    on_success: change
    on_failure: always
cache:
  directories:
    - $HOME/.cache/pip
