language: python
branches:
  only:
    - master
    - /^feature_.*$/
services:
- postgresql
python:
- '3.4'
addons:
  postgresql: "9.3"
install:
- pip install -r requirements.txt
before_script:
  - psql -c 'create database fud_test;' -U postgres
script:
  - python manage.py test --settings=fud.settings.travis
