
- name: Upgrade configuration (pg_hba.conf)
  template:
      src: pg_hba.conf.j2
      dest: "{{postgresql_config_path}}/pg_hba.conf"
      owner: "postgres"
      group: "postgres"
      mode: 0640
  notify: Restart PostgreSQL

- name: Upgrade configuration (postgresql.conf)
  template:
      src: postgresql.conf.j2
      dest: "{{postgresql_config_path}}/postgresql.conf"
      owner: "postgres"
      group: "postgres"
      mode: 0640
  notify: Restart PostgreSQL